### ISSUE TITLE
Add Git tags to generate sift releases in GitHub

### ISSUE THREAD

**Issue by jetm** [svent/sift#1]
Hello,

Could you add Git tags to generate [sift releases](https://github.com/svent/sift/releases) in GitHub?

With sift GitHub releases [I could know](https://github.com/svent/sift/releases.atom) when to update [sift Arch Linux package](https://aur.archlinux.org/packages/sift/).

Thanks in advance.

**Comment by svent** [comment]
Hi, thanks for creating a package for Arch Linux!
I just tagged the current version and will tag all future sift releases.

**Comment by jetm** [comment]
@svent: Thanks! I will modify the package to start getting the future sift releases.
