### ISSUE TITLE
Support for searching only in filenames, not in file content

### ISSUE THREAD

**Issue by moon-musick** [svent/sift#10]
Hi,

I found `sift` recently, liked it immediately and introduced it to several developers at the company I work for; they used `ack` with `vim` before and now were able to replace it almost completely with `sift`.

I've been asked though about an option to emulate `ack -g` behaviour, i.e. find files with names/paths matching pattern and only that (do not check the contents). Is there any possible option combination I might have not noticed so that `sift` could do that without any modification? Or if there isn't, is it doable to add something like that? Unfortunately my Golang foo is not strong enough to implement it myself and just send a PR.

Thanks in advance for any info on that.

**Comment by svent** [comment]
sift supports searching in pathnames with the `--path` option, so you can replicate that part of ack's `-g` option. I guess what really is missing is the something like the option `-f` to only list files matching the path search criteria without looking at the content.
That way you could also use all other file filtering options (--ext, --path, etc.) and then just list the matching files.

You can almost emulate ack's behavior:
ack: `ack -g PATTERN`
sift: `sift --path PATTERN ".*" -l`
Of course this a workaround, and it does work for empty files.

Once I am sure that I understand exactly what feature you need, I will implement the missing option(s).

**Comment by moon-musick** [comment]
`sift --path PATTERN ".*" -l` gets the job done well enough, thank you :)

I guess we would enjoy having the `-f` option equivalent too, and if you feel like implementing it someday, that is great news. The speed advantages of `sift` make it hard to get back to using slower tools, even if only for smaller tasks.

**Comment by svent** [comment]
Good to hear that the workaround helps so far - I will implement the `-f` option in a future release.

Thanks for your help to make sift more popular!
