### ISSUE TITLE
Doesn't work on Debian 10

### ISSUE THREAD

**Issue by StewAlexander-com** [svent/sift#106]
Doesn't work on Debian 10, if it does not sure how to get it to work... tried ./sift -x log error ... nothing

**Comment by yesmar** [comment]
That's weird, because sift 0.9.0 is working for me on Buster.

**Comment by drichardson** [comment]
Also can confirm it works for me on Debian 10 buster.

**Comment by StewAlexander-com** [comment]
Don't have time to further pursue ... apparently it's working anyhoo
