### ISSUE TITLE
Suppress very long lines error

### ISSUE THREAD

**Issue by mwean** [svent/sift#16]
Is there any way to suppress these errors?

```
Error: cannot process data from file 'some/file.txt': file contains very long lines (no newline in 262144 bytes)
```

I'm getting tons of these errors, and it makes it hard to see the actual results.

**Comment by svent** [comment]
If the error is caused by binary files, you could use the option `--binary-skip`. Alternatively you could suppress all errors by ignoring stderr (`sift ... 2>/dev/null`).
I will think about more options to handle this specific problem.

**Comment by mwean** [comment]
Yeah, they're not binary files, just minified js and css files. I'll use the stderr redirect for now.

**Comment by svent** [comment]
You could also configure sift to ignore minified css/js files (as long as the filename indicates that they are minified) by editing the .sift.conf config file or executing `sift --exclude-files '*.min.css' --exclude-files '*.min.js' --write-config`.

**Comment by richrumble** [comment]
Same with very long CSV files... Error: cannot process data from file 'file.csv: file contains very long lines (no newline in 262144 bytes) . Grep never complains, just sayin' :) What is the equivalent suppression for windows? Can you still redirect findings to a file as well as stderr to > nul?
sift.exe string_x file.csv >output.csv

**Comment by svent** [comment]
`sift ... > results.csv 2> NUL` should work on windows. One of the next versions of sift will include a better solution.

**Comment by svent** [comment]
As of version 0.4.0 sift supports two new options:
- `--err-skip-line-length` to skip these errors
- `--blocksize` to specify a larger blocksize, allowing to search files with very long lines.
  Example: `--blocksize 10M`

**Comment by sergeevabc** [comment]
Last run of ```sift --color --multi-line --line-number --blocksize 20M pattern``` over a a single 11 MiB file resulted in a unresponsive machine then switched off by hand. Fortunately, no loss of data.
