### ISSUE TITLE
colors in Windows console

### ISSUE THREAD

**Issue by jgranduel** [svent/sift#21]
Hi, 

when using the --color option, if the search is killed with Ctrl-C, color is/might be kept on the shell (tested on Windows-7, with cmd.exe and [cmder](http://cmder.net)/PowerShell; cannot reproduce on Linux/bash xterm).
Best regards

**Comment by svent** [comment]
Hi,
colored output is not natively supported on Windows as that would require platform specific code. I wondered how it worked at all when I first read this - cmder seems to emulate a unix compatible terminal. As I never experienced this problem on Linux I fear that the emulation (or Windows) behaves somehow different. I tried to reproduce this with cmder but did not succeed so far.
I could imagine a (rather ugly) workaround for this, but that would require intercepting Ctrl-C and I would really like not to implement that (if the user hits Ctrl-C sift should just exit and not try to perform some magic).
I fear there will be no good solution in the near future.
