### ISSUE TITLE
option like '--as-unixpath'

### ISSUE THREAD

**Issue by kybin** [svent/sift#22]
Hi, thank you for this program.

I'm using it in windows. So It shows windows style path. Like below..

`some\path\to\file`

But I need path like this.

`some/path/to/file`

It should be great if there is an option for this conversion.

Thanks.

**Comment by svent** [comment]
Hi,
this should be quite easy to implement, and it might be a nice feature to be able to force the exact output format across all operating systems.
This will be included in one of the next versions.

**Comment by svent** [comment]
The new option `--output-unixpath` is available as of version 0.4.1.

**Comment by kybin** [comment]
thank you!
