### ISSUE TITLE
Request: file name format

### ISSUE THREAD

**Issue by lecheel** [svent/sift#25]
if possible support short filename like Ag
![2015-10-08 11 06 31](https://cloud.githubusercontent.com/assets/148137/10356725/a8b33e96-6dac-11e5-8d3b-641e543260ab.png)

**Comment by lecheel** [comment]
sorry :-p which already have --group as same feature

**Comment by svent** [comment]
I forgot to reply yesterday - good to hear that you found the option and that it does what you want.

**Comment by lecheel** [comment]
Thanks it works
