### ISSUE TITLE
Floating point exception ON SLES10

### ISSUE THREAD

**Issue by dsaputra** [svent/sift#28]
I tried to run sift on my production server which is running SUSE Enterperise Linux 10 and it give me Floating Point Exception error.

svr001:/home/software/sift # ./sift information LICENSE
Floating point exception

**Comment by svent** [comment]
Could you test whether this also happens if you execute `sift -V` or `sift --help`?
sift does not use any floating point values, so I guess this is a problem of the go runtime.
I will try to reproduce it in the next days.

**Comment by svent** [comment]
I cannot test this as I do not have access to a machine with SLES 10, but this should be the same problem Go programs have on CentOS 5.x (see #29) - the kernel version is quite old.
As I cannot fix this in sift itself, SLES 10 will remain unsupported.

**Comment by dsaputra** [comment]
Hi Sven, Ok Noted, Thank you

Best Regards
Dharma Saputra
