### ISSUE TITLE
Readdir(-1) doesn't scale well

### ISSUE THREAD

**Issue by chowey** [svent/sift#32]
The other day I needed to grep through a directory with ~900,000 files in it. This directory is painful to deal with using any tool, even `ls`. So I fired up `sift`, thinking it would perform well.

It took _minutes_ before it returned the first result. Mind you the results were coming fast once I was over that initial hump.

Looking at the [source code](https://github.com/svent/sift/blob/master/sift.go#L160), I see that it uses `dir.Readdir(-1)` to recursively scan directories. Needless to say this doesn't scale well.

Could we use something more scalable, such as `dir.Readdir(255)` with a loop?

Example fix:

``` go
for {
    entries, err := dir.Readdir(255)
    if err == io.EOF {
        break
    }
    if err != nil {
        errorLogger.Printf("cannot read directory '%s': %s\n", dirname, err)
        return
    }
    // ... rest of code as usual
}
```

**Comment by svent** [comment]
Thanks for this suggestion - as you say no tool handles such a directory well, but I will check whether the performance of sift can be improved for this use case.

**Comment by svent** [comment]
I tested this with one million small files in a single directory: If everything is in the file system cache, the call to Readdir() only needs about 2 seconds. If the cache is not filled, it took much longer and sift did not start processing the files.
As of version 0.4.1, sift reads large directories in chunks of 256 entries and starts processing them after the first chunk has been read.
Thanks again for this suggestion!
