### ISSUE TITLE
Formatting output like ack

### ISSUE THREAD

**Issue by phb95** [svent/sift#33]
Thanks for this great and fast tool.
I have been looking for options to customize the output of sift.
I'd like it to match the way ack displays its results ie the file name on a separate line after a newline followed by matches on individual lines.
Is it possible ?

**Comment by svent** [comment]
The option `--group` should hopefully do what you want, see also #17 where this was first requested.

**Comment by phb95** [comment]
Apologies, I forgot to check the closed issues, and missed it in the documentation.
Thanks for your answer.
