### ISSUE TITLE
switch for path separator ALT detect cygwin

### ISSUE THREAD

**Issue by msloth** [svent/sift#37]
Hi, thanks for sift, very nifty.

I use Windows 7 + cygwin (64-bit).

I typically search through a large code base for a string, then copy-paste the filename to `open <thefilepath>`. Sift does not output the correct path separator in this case, so that doesn't work.

Here's a sample output from `grep`:

```
[0]~/temp/windowgroomer:
 [master]>grep -r win .
./.git/hooks/pre-rebase.sample:9:# The hook is called with the following parameters:
./.git/hooks/pre-rebase.sample:15:# merged to 'next' branch from getting rebased, because allowing it
./.git/hooks/pre-rebase.sample:123:    not want to rewind it.
```

With sift, this would look like this:

```
[1]~/temp/windowgroomer:
 [master]>sift --line-number --color --type cc --context=1 win .
wm\nativewindow.h-2-
wm\nativewindow.h:3:A cross-platform way to represent and modify native windows.
wm\nativewindow.h:4:We can't use QxtWindowSystem because we need Mac support and window resizing.
wm\nativewindow.h-5-*/
--
wm\nativewindow.h-48-private:
wm\nativewindow.h:49:  WindowId window;
wm\nativewindow.h-50-
```

The difference being that sift detects windows OS but not Cygwin, hence uses Windows path separators.

Version:

```
[0]~/temp/windowgroomer:
 [master]>sift -V
sift 0.4.1 (windows/amd64)
Copyright (C) 2014-2015 Sven Taute
....
```

It would be awesome if sift could either detect Cygwin and use the cygwin unix-like path separators, or if I can pass eg `--path-separator=/`to sift.

Thanks!

**Comment by svent** [comment]
The latest version (0.4.1) contains the option `--output-unixpath` - I hope that one does what you need here.
