### ISSUE TITLE
Deep merge local & global config files

### ISSUE THREAD

**Issue by Niluge-KiWi** [svent/sift#4]
Currently the local config file is merged with the global one at only one level: array options are only taken from local config, ignoring the global config.

``` shell
$ cat ~/.sift.conf
{"ExcludeDirs": [ "1"]}
$ cat ~/test/.sift.conf
{"ExcludeDirs": [ "2"]}
$ cd ~/test
$ cat 1/file
test
$ cat 2/file
test
$ sift test
1/file:1:test
```

We would instead expect that both config files be deeply merged and thus both directories "1" and "2" be ignored.

**Comment by svent** [comment]
I guess it is up to personal taste what one would expect here. It should definitely be possible to override global exclusions in a local config, i.e. to reset the exclusions and search everywhere for example. This is currently only possible if the settings do not get merged.
As there is no "correct" way to handle this (in my opinion) I will keep the current behavior here.

**Comment by Niluge-KiWi** [comment]
We could have an option that enable deep merging.
Either globally, or per file merged, or even per option (although this one requires structural change of the config file to make room to express that...).

Even only the global flag would be enough for my use case: it would be fine to have "always deep merge" semantic for all my options for all the config files.

**Comment by llelf** [comment]
@svent but right now there's no way to merge, is there?

FWIW, +1 for it being totally counter-intuitive.
