### ISSUE TITLE
Feature - Add option to ignore the config file

### ISSUE THREAD

**Issue by Rican7** [svent/sift#40]
[Ack](http://beyondgrep.com) has a `--noenv` option to allow for ignoring any configuration/settings defined in the environment or in the `.ackrc` file. Since **sift** has a similar ability to configure it's usage through a config file, it would be a nice addition to be able to ignore it temporarily.

This is very useful for testing queries with different settings or for relying on a default behavior in a script.

---

PS: Great tool! I love it!

**Comment by svent** [comment]
Thanks for the feedback and the suggestion, this is a good idea and I will implement it.

**Comment by Rican7** [comment]
Thanks for the quick response! Great to hear! :smiley:

**Comment by svent** [comment]
I just released version 0.5.0 with the new option `--no-conf` to ignore existing config files.

**Comment by Rican7** [comment]
Awesome! Thanks!
