### ISSUE TITLE
calling sift with clojure.java.shell/sh

### ISSUE THREAD

**Issue by drorbemet** [svent/sift#43]
This issue might not be specific to sift but I don't know whom to ask first.
There seems to be a difference between grep and sift.

grep works fine when called form java:
`(clojure.java.shell/sh "grep" "-ir" "patter in a text file")`
=> {:exit 0, :out "matches ..." :err "}

but sift exits out of some reason:
`(clojure.java.shell/sh "sift" "-i" "pattern in a text file")`
=> {:exit 1, :out "", :err ""}

I run these on linux bash in a leiningen repl.

**Comment by drorbemet** [comment]
The working directory has to be passed to sift explicitly:
`(clojure.java.shell/sh "sift" "patter in a text file" "/working directory")`

**Comment by svent** [comment]
I guess that clojure connects a pipe to STDIN of the executed command - without a target directory sift then detects that, reads from STDIN and quits.

to reproduce this on the command line:
`echo "abc" | grep -ir pattern`
`echo "abc" | sift -i pattern`

Thanks for documenting the solution here.
