### ISSUE TITLE
Feature request: --not-in-match=PATTERN

### ISSUE THREAD

**Issue by LarryBattle** [svent/sift#44]
## Feature Request:

It would be great to have an option to where you could filter the matches based on if they don't match a pattern. Negative lookahead support could solve this problem but golang doesn't support it natively. 
### Option:

-E, --not-in-match=PATTERN  Return matches that don't contain the submatch
#### Content of testFile.txt

```
1: <input type="button" class="btn">
2: <input class="btn">
```
#### Command

```
sift -e "<input [^>]+>" -E " type=" ./testFile.txt
```
#### Output:

```
testFile.txt 
2: <input class="btn">
```
### Pseudo Code

```
matches.filter(x => !(not_in_match_pattern).test(x))
```

**Comment by svent** [comment]
If I got this correctly, the output would be the same as the following command:
`sift -e "<input [^>]+>" testfile.txt | sift -v " type="`

If you want to use one call to sift with an integrated option, you can use conditions for this. Conditions are much more flexible than one special option for this case. The command looks like:
`sift -e "<input [^>]+>" --not-surrounded-within "0: type=" testfile.txt`
Not surrounded by X within zero lines is equivalent to "the same line does not match X" here.

Would this support your use case, or did I miss something?

**Comment by LarryBattle** [comment]
Yup, both of those worked. 
I guess I just didn't understand how `--not-surrounded-within` and `--surrounded-within` worked exactly.
