### ISSUE TITLE
Request: Implement full word option

### ISSUE THREAD

**Issue by MiguelLatorre** [svent/sift#46]
It would be nice to have the option "-w" like have "grep", "ack" and "ag":

grep --help
  -w, --word-regexp         force PATTERN to match only whole words

ack --help
  -w, --word-regexp             Force PATTERN to match only whole words

ag --help
  -w --word-regexp        Only match whole words

**Comment by svent** [comment]
Thanks for your suggestion - I will implement this option.

**Comment by svent** [comment]
Implemented as of version 0.7.0.
