### ISSUE TITLE
Feature - Add `-g PATTERN` like option to enable smart file listing

### ISSUE THREAD

**Issue by Rican7** [svent/sift#47]
Both [Ack](http://beyondgrep.com) and [The Silver Searcher](http://geoff.greer.fm/ag/) have a `-g PATTERN` command that enables for fast file listing based on expression matching the file path itself, while still keeping in mind configuration settings (like ignoring certain file types from showing in results).

While this `-g` flag enables these applications to perform quite _differently_ (matching against path/filename rather than actual contents), it allows them to be used in interesting contexts, such as the [driver to CtrlP indexing](https://github.com/kien/ctrlp.vim). More info regarding the benefits of this use case are spelled out in @thoughtbot's blog post [_"Faster Grepping in Vim"_](https://robots.thoughtbot.com/faster-grepping-in-vim).

**Comment by svent** [comment]
Thanks for the suggestion and background info. This is somehow related to #10 - the option `--path` can be used to match the file paths against a regex pattern, but the option to just list the files that would be searched is still missing. That option ("just list files") will be implemented in the near future.

**Comment by Rican7** [comment]
Oh wow, sorry for missing #10.

Well thanks for the quick response and for considering the new feature :smiley:

**Comment by svent** [comment]
I implemented this with version 0.7.0, please see the [release notes](https://github.com/svent/sift/releases/tag/v0.7.0) for details.

**Comment by Rican7** [comment]
You're awesome! Thanks!
