### ISSUE TITLE
Request: use captured matches to specify name when writing output to file

### ISSUE THREAD

**Issue by orgoed** [svent/sift#48]
The --output option to  write output to the specified file or network connection is really handy. It would be fantastic if Sift could use captured matches to specify the file name. For example:

``` xml
<book id="bk102">
  <author>Ralls, Kim</author>
  <title>Midnight Rain</title>
  <genre>Fantasy</genre>
  <price>5.95</price>
  <publish_date>2000-12-16</publish_date>
  <description>A former architect battles corporate zombies,
  an evil sorceress, and her own childhood to become queen
  of the world.</description>
</book>
```

`sift -m '<book id="(.*?)">.*?<author>(.*?)</author>' books.xml --replace '$2' -o $1.txt`

**Comment by svent** [comment]
Thanks for the suggestion. I do like the idea, but this would be quite complex to implement as writing to more than one file was never intended in sift.
Another problem is that I already see users "destroying" their file system when something with the captured matches goes wrong.

I will think about this if a future version should bring a complete redesign of the output logic.
