### ISSUE TITLE
Feature Request: Implement Option to Limit # of Processor Used

### ISSUE THREAD

**Issue by fligi7** [svent/sift#50]
Any way to implement a feature to control/limit the amount of processor used by the tool? That would be really useful on systems where you need to be mindful of CPU usage during searches.

**Comment by svent** [comment]
You can use the option `-j/--cores` to limit the number of CPU cores used - is that what you searched for?

**Comment by fligi7** [comment]
I searched the help file multiple times before posting this and somehow didn't see that. Apologies, that is what I was looking for.
