### ISSUE TITLE
-e can't be passed a pattern starting with a hyphen

### ISSUE THREAD

**Issue by vith** [svent/sift#52]
``` shell-session
❯ sift -e '-----BEGIN' ~/.ssh/ 
Error: expected argument for flag `-e, --regexp', but got option `-----BEGIN'
```

Throwing a useless capture group at the start makes it work.

**Comment by svent** [comment]
Unfortunately, sift currently does not support arguments beginning with `--` as value for options - but it does supporting searching for those terms: `sift -- '-----BEGIN' ~/.ssh/`.

Searching for terms starting with `--` using the option -e will not work, but I think that is a very rare case. Changing the option parsing code to support this would be more work than it is worth in my opinion, so this will likely not change in the near future.

If you want to search for multiple search terms, you  can use `-f` to read them from a file - this does also support search terms starting with `--`.

**Comment by vovcacik** [comment]
You can also escape the hyphens `sift '\-\-\-\-\-BEGIN' ~/.ssh/`.
