### ISSUE TITLE
Request: Smartcase option

### ISSUE THREAD

**Issue by ajcrites** [svent/sift#56]
I find smartcase (ignore case unless a capital letter is used) to be very useful for code searching. I realize that this can be done with something like `[tT]erm`, but this requires you to disable ignore-case -- something I generally use by default. It's also a lot more typing.

A smartcase option would be useful.  `sift --smart-case term` searches, term, Term, TERM, etc. `sift --smart-case Term` will only search for Term.

**Comment by svent** [comment]
Thinks for your suggestion and PR.
I just released sift 0.8.0 supporting smart case, please see my comment on #57 regarding the slightly different implementation.
