### ISSUE TITLE
Feature: Print column number

### ISSUE THREAD

**Issue by MiguelLatorre** [svent/sift#60]
Use case: editors (or external tools), would have information to go to the line and column where the hit is.
Using ack as an example:

<pre>
$ ack --no-group --python weird
personal/grep.py:412:weird = any(titem == 'PA' for (titem, item) in values[orig])
</pre>

<pre>
$ ack --no-group --python <b>--column</b> weird
personal/grep.py:412:17: weird = any(titem == 'PA' for (titem, item) in values[orig])
</pre>

**Comment by svent** [comment]
Thanks for the suggestion - I just implemented this and it seems to work, but I want to give it some more testing. This will definitely be in the next version that includes new features (0.8).

**Comment by MiguelLatorre** [comment]
Thanks! I appreciate it.

**Comment by svent** [comment]
The option `--column` is available as of sift version 0.8.0.
