### ISSUE TITLE
Feature - Add option to get a global result count

### ISSUE THREAD

**Issue by Rican7** [svent/sift#62]
**Sift** already includes an option (`--count`) to display a simple **count** of results per file. Unfortunately, there's no easy way to then get a single count of all found matches.

**Ack** currently has this ability by combining the `--count` and `--no-filename` options, which is quite honestly very awkward, but it works.

The alternative is to pipe the **Sift** output to a script that adds all of the lines in the output. Unfortunately, that's quite awkward to do in a linux shell, let alone Windows:

![screen shot 2016-01-08 at 11 08 05 am](https://cloud.githubusercontent.com/assets/742384/12202940/64eccb0a-b5fa-11e5-97f7-60297f1c5082.png)

If this feature/option were to be added to **Sift**, I'd personally suggest not following the **Ack** way of doing things, as the dual options are awkward and hard to discover, but that's just me. :stuck_out_tongue:

**Comment by svent** [comment]
I think Ack's behavior when combining the options `--count` and `-no-filename` is quite surprising and I would not want to implement it that way, but sift's option `--stats` should do the trick:

```
sift Copyright --stats
[... results ...]
10 files processed
10 files match
14 matches found
```

To just get the number of matches (stats are printed to STDERR to separate them from the matches):

```
sift Copyright --stats -o /dev/null 2>&1 | sift '(\d+)\smatches' --replace '$1'
14
```

**Comment by Rican7** [comment]
Oh, nice! I didn't see `--stats`. Good call. Thanks!
That might still prove to be a _little_ awkward for scripting to use `sift` as an external tool, but for a CLI use case just needing a visual report, it's quite easy. Thanks!

**Comment by svent** [comment]
Of course I could add an option to only print the number of matches, but I think sift has enough options already and this is a good application for the unix philosophy "do one thing and do it well". It should be easy enough to solve this with simple scripting and sift should not try to have an option for everything.

**Comment by Rican7** [comment]
I absolutely agree. Thanks for the timely and thoughtful responses. :smiley:
