### ISSUE TITLE
Using colon as separator for file names and matches not Windows friendly

### ISSUE THREAD

**Issue by ddevienne** [svent/sift#68]
We're using sift process some C++ sources to record where some C++ identifiers are defined (which files). The generated output is later read by a program, which splits the line on column to get the file path on the left, and the captured identified name on the right.

But with Windows paths, and the colon following the drive letter, we now have not 2 but 3 parts in the line, needing special cases between Windows and Linux.

Is there a way to avoid this, and make swift's output more easily machine parse-able in a more cross platform manner?

**Comment by svent** [comment]
Thanks for your feedback - I will implement a solution in an upcoming version. I fear there is no good workaround with the current version.

**Comment by svent** [comment]
As of version 0.9, sift supports this option.
