### ISSUE TITLE
Benchmarks are non-sense

### ISSUE THREAD

**Issue by lunemec** [svent/sift#7]
Hello,

I took a look at your benchmarks and they don't quite make sense. You claim you managed to read 35GB of data split over 32 files in under 0.5s? How is this possible? You'd need read speeds of over 70GB/s to achieve this. On normal machine with PCI-Express 3.0 x16 you have ~4GB/s bandwidth, and this is the fastest interface in the computer. 

Can you elaborate how you measured these magic results and what setup you used?
Thank you

**Comment by svent** [comment]
I am sorry, but maybe you should do some more research before accusing other people of publishing false data.
PCI Express 3.0 x16 has a higher memory bandwidth than 4GB/s - but this is even irrelevant for these benchmarks.
The paragraph directly above the benchmark results clearly states the reason:

> All searches were performed with the complete data files cached by the operating system. Three runs per test were performed and the best result was taken.

This means that the data is read from memory and not from disk (which would make no sense as that would not benchmark the tools/algorithms but the used harddisks).

> The weblog searches were done on a big server, while the rest was done on a desktop system.

The mentioned weblog search was done on a server with some more CPUs and enough memory to hold the complete test data in the file system cache.

**Comment by lunemec** [comment]
Alright, I was mistaken about PCI-Express, with version 3.0 and x16 it has bandwidth of ~31GB/s. That does not matter. The reason of my "accusations" :) is that I've tried sift on our server production logs. I tried 1 file of 1.5GB against grep, also cached in memory. Grep was done in 0.7s, and sift in 5s. These numbers are repeatable. When searching 2 files of the same size sift took again 5.2s and grep 1.2s. This led me to question how were you able to read 32GB. I wanted to send you my logs, but they contain sensitive data, but I think any apache/nginx logs would do to simulate this again.

Don't mistake me, I want sift to be faster and use it, but my benchmarks don't fall even close to your's.

**Comment by GeertJohan** [comment]
@lunemec: I think you should add the commands that you executed so anyone can attempt to reproduce.

**Comment by lunemec** [comment]
the commands:
`time sift setAttributes logfile > /dev/null`
`time grep setAttributes logfile > /dev/null`

**Comment by dundee** [comment]
@svent Can you add info about your HW configuration to the benchmarks page? 

@lunemec It seems that sift is so fast in the first scenario (32files of total 35GB), because it's many small chunks. I just tried the same query for 4 1GB files and it gave me 0.878s. When I did the same query for one 4GB file, it was 1.793s (grep 2.263s). So probably concurrency is the key benefit of sift. 

Tested on quadcore i5-4210U, 8GB RAM.
