### ISSUE TITLE
[WORKAROUND] Lookbehind and lookahead possible?

### ISSUE THREAD

**Issue by sergeevabc** [svent/sift#84]
I/O
```
echo Saving to: 'hello.sql' | sift --only-matching (?<=').+(?=')
The filename, directory name, or volume label syntax is incorrect.
```
Expected
```
hello.sql
```

It seems error occurs because ```cmd.exe``` fails to process special chars, right?

However the following piece confuses me whether issue is about ```cmd.exe``` of Sift itself.
```
echo Saving to: 'hello.sql' | sift --only-matching -e "(?<=').+(?=')"
Error: cannot parse pattern: error parsing regexp: invalid or unsupported Perl syntax: `(?<`
```

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by svent** [comment]
You are right, the first example does not work due to escaping problems.
The second example is "correct": sift does not support lookbehind/lookahead assertions.
The task of extracting the filename is possible though:
```
echo Saving to: 'hello.sql' | sift "'(.+)'" --replace "$1"
hello.sql
```

**Comment by sergeevabc** [comment]
Thank you for a workaround, Sven.
Should I rename this issue to “Implement support of lookbehind/lookahead”?

**Comment by svent** [comment]
That limitation comes from the Go RegEx engine that I use in sift, so unfortunately it cannot easily be fixed.

**Comment by sergeevabc** [comment]
Oh, it makes life so harder.
For example, ```(\w+)(\.\w+)+(?!.*(\w+)(\.\w+)+)``` to get a filename from URL does not work.
More or less workaround is ```[^\/?#]*\.[^\/?#]*(\?.*)?(\#.*)?$```.
