### ISSUE TITLE
tasks runner / macros and pre-defined seeds of patterns

### ISSUE THREAD

**Issue by roscopecoltran** [svent/sift#88]
Hi,

Hope you are all well !

I am using sift now a couple of months, and love it, and recently I wanted to automate some tasks, mainly through git hooks, to sift the source code of some repositories, to match some patterns like in this example, https://github.com/porter-io/tagg-python/blob/master/tagg/default_defs.json, and to write a a yaml dump adding some metainfo to my repos. 

Ultimately, I would like also to generate some dockerfiles based on dependencies parsed from the code, like from the headers in the source code or by parsing the CMakeLists.txt, packages.json or requirements.txt, so I just need a structured yaml file in order to compose a docker-compose.yaml or Dockerfile.

So, I see like 3 pre-requisites:
- trigger some sifting macros or tasks per keyword or topic matching
- trigger some external services to complete the final output file, metainfo.yaml 
- be able to create some seeds/stopword list in a yaml/json file

refs:
- Task runners 
   - https://github.com/tj/robo
   - https://github.com/dogtools/dog

- code static analysis
   - https://github.com/bndr/pipreqs (Python)
   - https://github.com/nexB/scancode-toolkit (Python)
   - https://github.com/google/zoekt (Golang)

Are such seeds and macros be something worth to be added in sift ? I am facing a kind of dilemna ^^ :-) 

Would u recommend/suggest a different approach ?

Have a great day and thanks for sift !

Cheers,
Richard

**Comment by svent** [comment]
Hi Richard,

thanks for you feedback!
I fear that this would add quite some complexity to sift and make sift much more than just a search tool.
While I am open to adding search-related features to sift, I try to focus on that area and prevent feature creep. New features should be quite generic and work for all kind of texts.

I think some custom code for this task might be better and more flexible than integrating all this directly into sift.

**Comment by roscopecoltran** [comment]
But I was talking about flexibility with those macros, yaml defined, where people can define and save some regex for further search tasks on recurrent patterns... 

So, sorry, I cannot get the depth or meaning of "**feature creep**", as it below an automated use, maybe I am dumb, so sorry about that...

Quiet irritating answer ! You can close the issue...

Thanks in advance.

**Comment by svent** [comment]
Your request is definitely not dumb, I just think that this is too complex to integrate it directly into sift.
