### ISSUE TITLE
Plus symbol is not matched

### ISSUE THREAD

**Issue by flamery** [svent/sift#98]
Create txt file containing:

QAhiNCZXB+f4
QAhiNCZXBf4

Search it:
sift  "QAhiNCZXB+f4"
New Text Document.txt:QAhiNCZXBf4

sift  "QAhiNCZXBf4"
New Text Document.txt:QAhiNCZXBf4

Expected output should be:

sift  "QAhiNCZXB+f4"
New Text Document.txt:QAhiNCZXB+f4

sift  "QAhiNCZXBf4"
New Text Document.txt:QAhiNCZXBf4

**Comment by svent** [comment]
The output is correct, as the input is treated as a regular expression by default. "B+" matches one or more "B" characters.

If you want to match exactly the string used as parameter, try the option -Q/--literal:
```
$ sift -Q "QAhiNCZXBf4"
test:QAhiNCZXBf4
$ sift -Q "QAhiNCZXB+f4"
test:QAhiNCZXB+f4
```

**Comment by flamery** [comment]
Thank you, Q flag solves the issue.
